language: node_js
node_js:
  - "lts/*"

sudo:
  required

install:
  - npm install -g solhint
  - npm install -g truffle
  - npm install -g ganache-cli
  
script:
  - ganache-cli -d -p 9545 &
  - npm run build
  - truffle test




